// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v7.34.0
// source: debugService.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "control";

export enum StateType {
  CYCLE_RESET = 0,
  CYCLE_STOPPED = 1,
  CYCLE_HOLD = 2,
  CYCLE_STARTED = 3,
  DISCONNECT = 4,
  ALARM = 5,
  UNRECOGNIZED = -1,
}

export function stateTypeFromJSON(object: any): StateType {
  switch (object) {
    case 0:
    case "CYCLE_RESET":
      return StateType.CYCLE_RESET;
    case 1:
    case "CYCLE_STOPPED":
      return StateType.CYCLE_STOPPED;
    case 2:
    case "CYCLE_HOLD":
      return StateType.CYCLE_HOLD;
    case 3:
    case "CYCLE_STARTED":
      return StateType.CYCLE_STARTED;
    case 4:
    case "DISCONNECT":
      return StateType.DISCONNECT;
    case 5:
    case "ALARM":
      return StateType.ALARM;
    case -1:
    case "UNRECOGNIZED":
    default:
      return StateType.UNRECOGNIZED;
  }
}

export function stateTypeToJSON(object: StateType): string {
  switch (object) {
    case StateType.CYCLE_RESET:
      return "CYCLE_RESET";
    case StateType.CYCLE_STOPPED:
      return "CYCLE_STOPPED";
    case StateType.CYCLE_HOLD:
      return "CYCLE_HOLD";
    case StateType.CYCLE_STARTED:
      return "CYCLE_STARTED";
    case StateType.DISCONNECT:
      return "DISCONNECT";
    case StateType.ALARM:
      return "ALARM";
    case StateType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Empty {
}

export interface InitRequest {
  cncNodeId?: number | undefined;
  cncNodeIpAddress?: string | undefined;
  cncPaths: number[];
  pollingRate?: number | undefined;
  cycleStopCommandAddress?: string | undefined;
  singleBlockCommandAddress?: string | undefined;
  singleBlockStatusAddress?: string | undefined;
  variables: VariableDefinition[];
}

export interface StateRequest {
  pathNumber: number;
}

export interface ConnectReply {
  state?: StatusReply | undefined;
  controllerName: string;
  version: string;
}

export interface StatusReply {
  success: boolean;
  message: string;
}

export interface MachineState {
  pathNumber: number;
  state: StateType;
  messageType?: string | undefined;
  message?: string | undefined;
}

export interface MachineEvent {
  state: StateType;
  pathNumber: number;
  sequenceNumber: number;
  programNumber: number;
  message?: string | undefined;
}

export interface VariablesRequest {
  path: number;
  variables: VariableDefinition[];
}

export interface VariableDefinition {
  id: string;
  address: string;
  size?: number | undefined;
}

export interface VariablesReply {
  variables: VariableValue[];
}

export interface VariableValue {
  id: string;
  address: string;
  value: string;
}

function createBaseEmpty(): Empty {
  return {};
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Empty {
    return {};
  },

  toJSON(_: Empty): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Empty>, I>>(base?: I): Empty {
    return Empty.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Empty>, I>>(_: I): Empty {
    const message = createBaseEmpty();
    return message;
  },
};

function createBaseInitRequest(): InitRequest {
  return {
    cncNodeId: undefined,
    cncNodeIpAddress: undefined,
    cncPaths: [],
    pollingRate: undefined,
    cycleStopCommandAddress: undefined,
    singleBlockCommandAddress: undefined,
    singleBlockStatusAddress: undefined,
    variables: [],
  };
}

export const InitRequest: MessageFns<InitRequest> = {
  encode(message: InitRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cncNodeId !== undefined) {
      writer.uint32(8).uint32(message.cncNodeId);
    }
    if (message.cncNodeIpAddress !== undefined) {
      writer.uint32(18).string(message.cncNodeIpAddress);
    }
    writer.uint32(26).fork();
    for (const v of message.cncPaths) {
      writer.uint32(v);
    }
    writer.join();
    if (message.pollingRate !== undefined) {
      writer.uint32(32).uint32(message.pollingRate);
    }
    if (message.cycleStopCommandAddress !== undefined) {
      writer.uint32(42).string(message.cycleStopCommandAddress);
    }
    if (message.singleBlockCommandAddress !== undefined) {
      writer.uint32(50).string(message.singleBlockCommandAddress);
    }
    if (message.singleBlockStatusAddress !== undefined) {
      writer.uint32(58).string(message.singleBlockStatusAddress);
    }
    for (const v of message.variables) {
      VariableDefinition.encode(v!, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InitRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInitRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.cncNodeId = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.cncNodeIpAddress = reader.string();
          continue;
        }
        case 3: {
          if (tag === 24) {
            message.cncPaths.push(reader.uint32());

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.cncPaths.push(reader.uint32());
            }

            continue;
          }

          break;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.pollingRate = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.cycleStopCommandAddress = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.singleBlockCommandAddress = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.singleBlockStatusAddress = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.variables.push(VariableDefinition.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InitRequest {
    return {
      cncNodeId: isSet(object.cncNodeId) ? globalThis.Number(object.cncNodeId) : undefined,
      cncNodeIpAddress: isSet(object.cncNodeIpAddress) ? globalThis.String(object.cncNodeIpAddress) : undefined,
      cncPaths: globalThis.Array.isArray(object?.cncPaths) ? object.cncPaths.map((e: any) => globalThis.Number(e)) : [],
      pollingRate: isSet(object.pollingRate) ? globalThis.Number(object.pollingRate) : undefined,
      cycleStopCommandAddress: isSet(object.cycleStopCommandAddress)
        ? globalThis.String(object.cycleStopCommandAddress)
        : undefined,
      singleBlockCommandAddress: isSet(object.singleBlockCommandAddress)
        ? globalThis.String(object.singleBlockCommandAddress)
        : undefined,
      singleBlockStatusAddress: isSet(object.singleBlockStatusAddress)
        ? globalThis.String(object.singleBlockStatusAddress)
        : undefined,
      variables: globalThis.Array.isArray(object?.variables)
        ? object.variables.map((e: any) => VariableDefinition.fromJSON(e))
        : [],
    };
  },

  toJSON(message: InitRequest): unknown {
    const obj: any = {};
    if (message.cncNodeId !== undefined) {
      obj.cncNodeId = Math.round(message.cncNodeId);
    }
    if (message.cncNodeIpAddress !== undefined) {
      obj.cncNodeIpAddress = message.cncNodeIpAddress;
    }
    if (message.cncPaths?.length) {
      obj.cncPaths = message.cncPaths.map((e) => Math.round(e));
    }
    if (message.pollingRate !== undefined) {
      obj.pollingRate = Math.round(message.pollingRate);
    }
    if (message.cycleStopCommandAddress !== undefined) {
      obj.cycleStopCommandAddress = message.cycleStopCommandAddress;
    }
    if (message.singleBlockCommandAddress !== undefined) {
      obj.singleBlockCommandAddress = message.singleBlockCommandAddress;
    }
    if (message.singleBlockStatusAddress !== undefined) {
      obj.singleBlockStatusAddress = message.singleBlockStatusAddress;
    }
    if (message.variables?.length) {
      obj.variables = message.variables.map((e) => VariableDefinition.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InitRequest>, I>>(base?: I): InitRequest {
    return InitRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InitRequest>, I>>(object: I): InitRequest {
    const message = createBaseInitRequest();
    message.cncNodeId = object.cncNodeId ?? undefined;
    message.cncNodeIpAddress = object.cncNodeIpAddress ?? undefined;
    message.cncPaths = object.cncPaths?.map((e) => e) || [];
    message.pollingRate = object.pollingRate ?? undefined;
    message.cycleStopCommandAddress = object.cycleStopCommandAddress ?? undefined;
    message.singleBlockCommandAddress = object.singleBlockCommandAddress ?? undefined;
    message.singleBlockStatusAddress = object.singleBlockStatusAddress ?? undefined;
    message.variables = object.variables?.map((e) => VariableDefinition.fromPartial(e)) || [];
    return message;
  },
};

function createBaseStateRequest(): StateRequest {
  return { pathNumber: 0 };
}

export const StateRequest: MessageFns<StateRequest> = {
  encode(message: StateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pathNumber !== 0) {
      writer.uint32(16).uint32(message.pathNumber);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pathNumber = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StateRequest {
    return { pathNumber: isSet(object.pathNumber) ? globalThis.Number(object.pathNumber) : 0 };
  },

  toJSON(message: StateRequest): unknown {
    const obj: any = {};
    if (message.pathNumber !== 0) {
      obj.pathNumber = Math.round(message.pathNumber);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StateRequest>, I>>(base?: I): StateRequest {
    return StateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StateRequest>, I>>(object: I): StateRequest {
    const message = createBaseStateRequest();
    message.pathNumber = object.pathNumber ?? 0;
    return message;
  },
};

function createBaseConnectReply(): ConnectReply {
  return { state: undefined, controllerName: "", version: "" };
}

export const ConnectReply: MessageFns<ConnectReply> = {
  encode(message: ConnectReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.state !== undefined) {
      StatusReply.encode(message.state, writer.uint32(10).fork()).join();
    }
    if (message.controllerName !== "") {
      writer.uint32(18).string(message.controllerName);
    }
    if (message.version !== "") {
      writer.uint32(26).string(message.version);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConnectReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConnectReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.state = StatusReply.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.controllerName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.version = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ConnectReply {
    return {
      state: isSet(object.state) ? StatusReply.fromJSON(object.state) : undefined,
      controllerName: isSet(object.controllerName) ? globalThis.String(object.controllerName) : "",
      version: isSet(object.version) ? globalThis.String(object.version) : "",
    };
  },

  toJSON(message: ConnectReply): unknown {
    const obj: any = {};
    if (message.state !== undefined) {
      obj.state = StatusReply.toJSON(message.state);
    }
    if (message.controllerName !== "") {
      obj.controllerName = message.controllerName;
    }
    if (message.version !== "") {
      obj.version = message.version;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ConnectReply>, I>>(base?: I): ConnectReply {
    return ConnectReply.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConnectReply>, I>>(object: I): ConnectReply {
    const message = createBaseConnectReply();
    message.state = (object.state !== undefined && object.state !== null)
      ? StatusReply.fromPartial(object.state)
      : undefined;
    message.controllerName = object.controllerName ?? "";
    message.version = object.version ?? "";
    return message;
  },
};

function createBaseStatusReply(): StatusReply {
  return { success: false, message: "" };
}

export const StatusReply: MessageFns<StatusReply> = {
  encode(message: StatusReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StatusReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatusReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StatusReply {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: StatusReply): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StatusReply>, I>>(base?: I): StatusReply {
    return StatusReply.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StatusReply>, I>>(object: I): StatusReply {
    const message = createBaseStatusReply();
    message.success = object.success ?? false;
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseMachineState(): MachineState {
  return { pathNumber: 0, state: 0, messageType: undefined, message: undefined };
}

export const MachineState: MessageFns<MachineState> = {
  encode(message: MachineState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pathNumber !== 0) {
      writer.uint32(8).uint32(message.pathNumber);
    }
    if (message.state !== 0) {
      writer.uint32(16).int32(message.state);
    }
    if (message.messageType !== undefined) {
      writer.uint32(26).string(message.messageType);
    }
    if (message.message !== undefined) {
      writer.uint32(34).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MachineState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMachineState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.pathNumber = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.state = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.messageType = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MachineState {
    return {
      pathNumber: isSet(object.pathNumber) ? globalThis.Number(object.pathNumber) : 0,
      state: isSet(object.state) ? stateTypeFromJSON(object.state) : 0,
      messageType: isSet(object.messageType) ? globalThis.String(object.messageType) : undefined,
      message: isSet(object.message) ? globalThis.String(object.message) : undefined,
    };
  },

  toJSON(message: MachineState): unknown {
    const obj: any = {};
    if (message.pathNumber !== 0) {
      obj.pathNumber = Math.round(message.pathNumber);
    }
    if (message.state !== 0) {
      obj.state = stateTypeToJSON(message.state);
    }
    if (message.messageType !== undefined) {
      obj.messageType = message.messageType;
    }
    if (message.message !== undefined) {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MachineState>, I>>(base?: I): MachineState {
    return MachineState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MachineState>, I>>(object: I): MachineState {
    const message = createBaseMachineState();
    message.pathNumber = object.pathNumber ?? 0;
    message.state = object.state ?? 0;
    message.messageType = object.messageType ?? undefined;
    message.message = object.message ?? undefined;
    return message;
  },
};

function createBaseMachineEvent(): MachineEvent {
  return { state: 0, pathNumber: 0, sequenceNumber: 0, programNumber: 0, message: undefined };
}

export const MachineEvent: MessageFns<MachineEvent> = {
  encode(message: MachineEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.state !== 0) {
      writer.uint32(8).int32(message.state);
    }
    if (message.pathNumber !== 0) {
      writer.uint32(16).uint32(message.pathNumber);
    }
    if (message.sequenceNumber !== 0) {
      writer.uint32(24).uint32(message.sequenceNumber);
    }
    if (message.programNumber !== 0) {
      writer.uint32(32).uint32(message.programNumber);
    }
    if (message.message !== undefined) {
      writer.uint32(42).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MachineEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMachineEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.state = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pathNumber = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.sequenceNumber = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.programNumber = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MachineEvent {
    return {
      state: isSet(object.state) ? stateTypeFromJSON(object.state) : 0,
      pathNumber: isSet(object.pathNumber) ? globalThis.Number(object.pathNumber) : 0,
      sequenceNumber: isSet(object.sequenceNumber) ? globalThis.Number(object.sequenceNumber) : 0,
      programNumber: isSet(object.programNumber) ? globalThis.Number(object.programNumber) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : undefined,
    };
  },

  toJSON(message: MachineEvent): unknown {
    const obj: any = {};
    if (message.state !== 0) {
      obj.state = stateTypeToJSON(message.state);
    }
    if (message.pathNumber !== 0) {
      obj.pathNumber = Math.round(message.pathNumber);
    }
    if (message.sequenceNumber !== 0) {
      obj.sequenceNumber = Math.round(message.sequenceNumber);
    }
    if (message.programNumber !== 0) {
      obj.programNumber = Math.round(message.programNumber);
    }
    if (message.message !== undefined) {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MachineEvent>, I>>(base?: I): MachineEvent {
    return MachineEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MachineEvent>, I>>(object: I): MachineEvent {
    const message = createBaseMachineEvent();
    message.state = object.state ?? 0;
    message.pathNumber = object.pathNumber ?? 0;
    message.sequenceNumber = object.sequenceNumber ?? 0;
    message.programNumber = object.programNumber ?? 0;
    message.message = object.message ?? undefined;
    return message;
  },
};

function createBaseVariablesRequest(): VariablesRequest {
  return { path: 0, variables: [] };
}

export const VariablesRequest: MessageFns<VariablesRequest> = {
  encode(message: VariablesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.path !== 0) {
      writer.uint32(8).uint32(message.path);
    }
    for (const v of message.variables) {
      VariableDefinition.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VariablesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVariablesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.path = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.variables.push(VariableDefinition.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VariablesRequest {
    return {
      path: isSet(object.path) ? globalThis.Number(object.path) : 0,
      variables: globalThis.Array.isArray(object?.variables)
        ? object.variables.map((e: any) => VariableDefinition.fromJSON(e))
        : [],
    };
  },

  toJSON(message: VariablesRequest): unknown {
    const obj: any = {};
    if (message.path !== 0) {
      obj.path = Math.round(message.path);
    }
    if (message.variables?.length) {
      obj.variables = message.variables.map((e) => VariableDefinition.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VariablesRequest>, I>>(base?: I): VariablesRequest {
    return VariablesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VariablesRequest>, I>>(object: I): VariablesRequest {
    const message = createBaseVariablesRequest();
    message.path = object.path ?? 0;
    message.variables = object.variables?.map((e) => VariableDefinition.fromPartial(e)) || [];
    return message;
  },
};

function createBaseVariableDefinition(): VariableDefinition {
  return { id: "", address: "", size: undefined };
}

export const VariableDefinition: MessageFns<VariableDefinition> = {
  encode(message: VariableDefinition, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.address !== "") {
      writer.uint32(18).string(message.address);
    }
    if (message.size !== undefined) {
      writer.uint32(24).uint32(message.size);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VariableDefinition {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVariableDefinition();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.size = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VariableDefinition {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      size: isSet(object.size) ? globalThis.Number(object.size) : undefined,
    };
  },

  toJSON(message: VariableDefinition): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.size !== undefined) {
      obj.size = Math.round(message.size);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VariableDefinition>, I>>(base?: I): VariableDefinition {
    return VariableDefinition.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VariableDefinition>, I>>(object: I): VariableDefinition {
    const message = createBaseVariableDefinition();
    message.id = object.id ?? "";
    message.address = object.address ?? "";
    message.size = object.size ?? undefined;
    return message;
  },
};

function createBaseVariablesReply(): VariablesReply {
  return { variables: [] };
}

export const VariablesReply: MessageFns<VariablesReply> = {
  encode(message: VariablesReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.variables) {
      VariableValue.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VariablesReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVariablesReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.variables.push(VariableValue.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VariablesReply {
    return {
      variables: globalThis.Array.isArray(object?.variables)
        ? object.variables.map((e: any) => VariableValue.fromJSON(e))
        : [],
    };
  },

  toJSON(message: VariablesReply): unknown {
    const obj: any = {};
    if (message.variables?.length) {
      obj.variables = message.variables.map((e) => VariableValue.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VariablesReply>, I>>(base?: I): VariablesReply {
    return VariablesReply.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VariablesReply>, I>>(object: I): VariablesReply {
    const message = createBaseVariablesReply();
    message.variables = object.variables?.map((e) => VariableValue.fromPartial(e)) || [];
    return message;
  },
};

function createBaseVariableValue(): VariableValue {
  return { id: "", address: "", value: "" };
}

export const VariableValue: MessageFns<VariableValue> = {
  encode(message: VariableValue, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.address !== "") {
      writer.uint32(18).string(message.address);
    }
    if (message.value !== "") {
      writer.uint32(26).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VariableValue {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVariableValue();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VariableValue {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: VariableValue): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VariableValue>, I>>(base?: I): VariableValue {
    return VariableValue.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VariableValue>, I>>(object: I): VariableValue {
    const message = createBaseVariableValue();
    message.id = object.id ?? "";
    message.address = object.address ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

/** CNC control + debugging service */
export type ControlServiceService = typeof ControlServiceService;
export const ControlServiceService = {
  /** Establish connection */
  connect: {
    path: "/control.ControlService/Connect",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: InitRequest): Buffer => Buffer.from(InitRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): InitRequest => InitRequest.decode(value),
    responseSerialize: (value: ConnectReply): Buffer => Buffer.from(ConnectReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): ConnectReply => ConnectReply.decode(value),
  },
  /** Establish connection to the cnc */
  connectControl: {
    path: "/control.ControlService/ConnectControl",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    requestDeserialize: (value: Buffer): Empty => Empty.decode(value),
    responseSerialize: (value: ConnectReply): Buffer => Buffer.from(ConnectReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): ConnectReply => ConnectReply.decode(value),
  },
  /** Terminates connection */
  disconnect: {
    path: "/control.ControlService/Disconnect",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    requestDeserialize: (value: Buffer): Empty => Empty.decode(value),
    responseSerialize: (value: StatusReply): Buffer => Buffer.from(StatusReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): StatusReply => StatusReply.decode(value),
  },
  /** Cycle start execution */
  cycleStart: {
    path: "/control.ControlService/CycleStart",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    requestDeserialize: (value: Buffer): Empty => Empty.decode(value),
    responseSerialize: (value: StatusReply): Buffer => Buffer.from(StatusReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): StatusReply => StatusReply.decode(value),
  },
  /** Single block execution */
  singleBlock: {
    path: "/control.ControlService/SingleBlock",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    requestDeserialize: (value: Buffer): Empty => Empty.decode(value),
    responseSerialize: (value: StatusReply): Buffer => Buffer.from(StatusReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): StatusReply => StatusReply.decode(value),
  },
  /** Cycle stop execution */
  cycleStop: {
    path: "/control.ControlService/CycleStop",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    requestDeserialize: (value: Buffer): Empty => Empty.decode(value),
    responseSerialize: (value: StatusReply): Buffer => Buffer.from(StatusReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): StatusReply => StatusReply.decode(value),
  },
  /** Get current machine state */
  getState: {
    path: "/control.ControlService/GetState",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: StateRequest): Buffer => Buffer.from(StateRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): StateRequest => StateRequest.decode(value),
    responseSerialize: (value: MachineState): Buffer => Buffer.from(MachineState.encode(value).finish()),
    responseDeserialize: (value: Buffer): MachineState => MachineState.decode(value),
  },
  /** Read variables (when paused) */
  getVariables: {
    path: "/control.ControlService/GetVariables",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: VariablesRequest): Buffer => Buffer.from(VariablesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): VariablesRequest => VariablesRequest.decode(value),
    responseSerialize: (value: VariablesReply): Buffer => Buffer.from(VariablesReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): VariablesReply => VariablesReply.decode(value),
  },
  /** Stream runtime events */
  subscribeEvents: {
    path: "/control.ControlService/SubscribeEvents",
    requestStream: false,
    responseStream: true,
    requestSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    requestDeserialize: (value: Buffer): Empty => Empty.decode(value),
    responseSerialize: (value: MachineEvent): Buffer => Buffer.from(MachineEvent.encode(value).finish()),
    responseDeserialize: (value: Buffer): MachineEvent => MachineEvent.decode(value),
  },
} as const;

export interface ControlServiceServer extends UntypedServiceImplementation {
  /** Establish connection */
  connect: handleUnaryCall<InitRequest, ConnectReply>;
  /** Establish connection to the cnc */
  connectControl: handleUnaryCall<Empty, ConnectReply>;
  /** Terminates connection */
  disconnect: handleUnaryCall<Empty, StatusReply>;
  /** Cycle start execution */
  cycleStart: handleUnaryCall<Empty, StatusReply>;
  /** Single block execution */
  singleBlock: handleUnaryCall<Empty, StatusReply>;
  /** Cycle stop execution */
  cycleStop: handleUnaryCall<Empty, StatusReply>;
  /** Get current machine state */
  getState: handleUnaryCall<StateRequest, MachineState>;
  /** Read variables (when paused) */
  getVariables: handleUnaryCall<VariablesRequest, VariablesReply>;
  /** Stream runtime events */
  subscribeEvents: handleServerStreamingCall<Empty, MachineEvent>;
}

export interface ControlServiceClient extends Client {
  /** Establish connection */
  connect(
    request: InitRequest,
    callback: (error: ServiceError | null, response: ConnectReply) => void,
  ): ClientUnaryCall;
  connect(
    request: InitRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ConnectReply) => void,
  ): ClientUnaryCall;
  connect(
    request: InitRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ConnectReply) => void,
  ): ClientUnaryCall;
  /** Establish connection to the cnc */
  connectControl(
    request: Empty,
    callback: (error: ServiceError | null, response: ConnectReply) => void,
  ): ClientUnaryCall;
  connectControl(
    request: Empty,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ConnectReply) => void,
  ): ClientUnaryCall;
  connectControl(
    request: Empty,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ConnectReply) => void,
  ): ClientUnaryCall;
  /** Terminates connection */
  disconnect(request: Empty, callback: (error: ServiceError | null, response: StatusReply) => void): ClientUnaryCall;
  disconnect(
    request: Empty,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: StatusReply) => void,
  ): ClientUnaryCall;
  disconnect(
    request: Empty,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: StatusReply) => void,
  ): ClientUnaryCall;
  /** Cycle start execution */
  cycleStart(request: Empty, callback: (error: ServiceError | null, response: StatusReply) => void): ClientUnaryCall;
  cycleStart(
    request: Empty,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: StatusReply) => void,
  ): ClientUnaryCall;
  cycleStart(
    request: Empty,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: StatusReply) => void,
  ): ClientUnaryCall;
  /** Single block execution */
  singleBlock(request: Empty, callback: (error: ServiceError | null, response: StatusReply) => void): ClientUnaryCall;
  singleBlock(
    request: Empty,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: StatusReply) => void,
  ): ClientUnaryCall;
  singleBlock(
    request: Empty,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: StatusReply) => void,
  ): ClientUnaryCall;
  /** Cycle stop execution */
  cycleStop(request: Empty, callback: (error: ServiceError | null, response: StatusReply) => void): ClientUnaryCall;
  cycleStop(
    request: Empty,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: StatusReply) => void,
  ): ClientUnaryCall;
  cycleStop(
    request: Empty,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: StatusReply) => void,
  ): ClientUnaryCall;
  /** Get current machine state */
  getState(
    request: StateRequest,
    callback: (error: ServiceError | null, response: MachineState) => void,
  ): ClientUnaryCall;
  getState(
    request: StateRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: MachineState) => void,
  ): ClientUnaryCall;
  getState(
    request: StateRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: MachineState) => void,
  ): ClientUnaryCall;
  /** Read variables (when paused) */
  getVariables(
    request: VariablesRequest,
    callback: (error: ServiceError | null, response: VariablesReply) => void,
  ): ClientUnaryCall;
  getVariables(
    request: VariablesRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: VariablesReply) => void,
  ): ClientUnaryCall;
  getVariables(
    request: VariablesRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: VariablesReply) => void,
  ): ClientUnaryCall;
  /** Stream runtime events */
  subscribeEvents(request: Empty, options?: Partial<CallOptions>): ClientReadableStream<MachineEvent>;
  subscribeEvents(
    request: Empty,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<MachineEvent>;
}

export const ControlServiceClient = makeGenericClientConstructor(
  ControlServiceService,
  "control.ControlService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ControlServiceClient;
  service: typeof ControlServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
